services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    ports:
      - "3306:3306"
    networks:
      - prestashop-net
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./data/:/docker-entrypoint-initdb.d/

  prestashop:
    image: prestashop/prestashop:1.7.8
    container_name: prestashop
    environment:
      DB_SERVER: mariadb
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWORD: root
      PS_INSTALL_AUTO: 0
      PS_DEV_MODE: 1
    ports:
      - "8080:80"
    networks:
      - prestashop-net
    depends_on:
      - mariadb
    volumes:
      - ./prestashop:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: prestashop
    ports:
      - "8081:80"
    networks:
      - prestashop-net

networks:
  prestashop-net:
