services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop_user
      MYSQL_PASSWORD: secure_password
    ports:
      - "3307:3306"
    networks:
      - prestashop-net
    volumes:
      - db_data:/var/lib/mysql

  prestashop:
    image: prestashop/prestashop:1.7.8
    container_name: prestashop
    environment:
      DB_SERVER: mariadb
      DB_NAME: prestashop
      DB_USER: prestashop_user
      DB_PASSWORD: secure_password
    ports:
      - "8080:80"
    networks:
      - prestashop-net
    depends_on:
      - mariadb
    volumes:
      - ./prestashop:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: prestashop
    ports:
      - "8081:80"
    networks:
      - prestashop-net

networks:
  prestashop-net:

volumes:
  db_data:
