version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    networks:
      - prestashop-net
    volumes:
      - mysql_data:/var/lib/mysql

  prestashop:
    image: prestashop/prestashop:1.7.8
    container_name: prestashop
    environment:
      DB_SERVER: mysql
    ports:
      - "8080:80"
    networks:
      - prestashop-net
    depends_on:
      - mysql
    volumes:
      - prestashop_data:/var/www/html

networks:
  prestashop-net:

volumes:
  mysql_data:
  prestashop_data:
