<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0njmgfp\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0njmgfp/appProdProjectContainer.php') {
    touch(__DIR__.'/Container0njmgfp.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container0njmgfp\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container0njmgfp\appProdProjectContainer([
    'container.build_hash' => '0njmgfp',
    'container.build_id' => '7d5fad37',
    'container.build_time' => 1729611518,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0njmgfp');
