<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHgkxq6x\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHgkxq6x/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHgkxq6x.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHgkxq6x\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHgkxq6x\appProdProjectContainer([
    'container.build_hash' => 'Hgkxq6x',
    'container.build_id' => '30ebd308',
    'container.build_time' => 1732271706,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHgkxq6x');
