<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4nxywwr\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4nxywwr/appProdProjectContainer.php') {
    touch(__DIR__.'/Container4nxywwr.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container4nxywwr\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container4nxywwr\appProdProjectContainer([
    'container.build_hash' => '4nxywwr',
    'container.build_id' => 'c3765e7b',
    'container.build_time' => 1730238042,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4nxywwr');
