<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGhfuwdl\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGhfuwdl/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGhfuwdl.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGhfuwdl\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGhfuwdl\appProdProjectContainer([
    'container.build_hash' => 'Ghfuwdl',
    'container.build_id' => '437d2cf3',
    'container.build_time' => 1732123364,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGhfuwdl');
