<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX6ogows\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX6ogows/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX6ogows.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX6ogows\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerX6ogows\appDevDebugProjectContainer([
    'container.build_hash' => 'X6ogows',
    'container.build_id' => 'b5734ad8',
    'container.build_time' => 1732271762,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX6ogows');
