name: Check for Linked Issue

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  check-linked-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Check for linked issue
      id: check_issue
      run: |
        PR_BODY=$(curl -s -H "Accept: application/vnd.github.v3+json" \
                         -H "Authorization: token ${{ secrets.LABEL_CHECK }}" \
                         https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
                         | jq -r .body)
        if [[ "$PR_BODY" =~ #[0-9]+ ]]; then
          issue_number=$(echo "$PR_BODY" | grep -o '#[0-9]\+' | head -n 1 | tr -d '#')
          echo "Linked issue found: $issue_number"
          echo "::set-output name=issue_number::$issue_number"
        else
          echo "No linked issue found"
          exit 1
        fi

    - name: Fail the job if no issue is linked
      if: steps.check_issue.outputs.issue_number == ''
      run: exit 1
