name: Check Linked Issue

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-linked-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Check if PR description contains linked issue
      uses: actions/github-script@v6
      with:
        script: |
          const prBody = context.payload.pull_request.body || "";
          const issuePattern = /(?:close[sd]?|fix[esd]?|resolve[sd]?|#\d+)/gi;
          
          if (!issuePattern.test(prBody)) {
            core.setFailed("Pull request does not link to any issue.");
          } else {
            console.log("PR description contains a linked issue.");
          }
