name: PrestaShop CI with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      # Set up Docker (this is automatically available on ubuntu-latest)
      - name: Verify Docker Compose installation
        run: |
          docker-compose --version

      # Run docker-compose to start the services
      - name: Start services with docker-compose
        run: |
          docker-compose up -d

      # Run basic tests (adjust for your project)
      - name: Run tests
        run: |
          curl --retry 5 --retry-connrefused --retry-delay 5 http://localhost:8080

      # Optionally, stop and clean up the Docker containers after the test
      - name: Stop and remove Docker containers
        run: |
          docker-compose down
