name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - docker-pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Pobieranie kodu źródłowego z repozytorium
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Logowanie do Docker Hub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Budowanie obrazu Dockerowego z Dockerfile
      - name: Build Docker Image
        run: |
          docker build -t piotreczek481/potter-shop:latest .

      # Pushowanie obrazu na Docker Hub
      - name: Push Docker Image
        run: |
          docker push piotreczek481/potter-shop:latest
